# Quantumult X
# SMZDM startup ad blocking
# Test rule based on captured startup requests.

hostname = s3.zdmimg.com

^https:\/\/s3\.zdmimg\.com\/cpm\/api\/v1\/advert_distribution\/get_all_advertise\?(?:[^&]*&)*zdm_template=cpm_iphone_homepage_0_open(?:&|$) url reject-dict
